---
# ============================================================
# HOSTNAME  →  {{ server_node }}-{{ server_location }}-{{ server_number }}
# ============================================================
server_node:     "node5"
server_location: "sweden"
server_number:   "005"

# ============================================================
# REMNAWAVE
# Install option: 1=panel+node, 2=только panel, 3=добавить node, 4=только node
# ============================================================
node_domain:                 "node5.mxist.store"
panel_ip:                    "87.121.221.25"
node_certificate:            "eyJub2RlQ2VydFBlbSI6Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQmREQ0NBUm1nQXdJQkFnSUhBWGNqZ29ZVk9EQUtCZ2dxaGtqT1BRUURBakFnTVI0d0hBWURWUVFEREJWMFxuWmtaWlltMURkREJ6YTE4NFNqQkdZbGRqT0Rjd0hoY05Nall3TXpBeE1UWXpOREl4V2hjTk1qa3dNekF4TVRZelxuTkRJeFdqQW1NU1F3SWdZRFZRUUREQnRWUXpkaFpHcFJiazFvWHpRdFFuSkRSMFUwVVV0d0xVTlRWRTR3V1RBVFxuQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUnVaMi9UWHFVVmlRbjFiTjcwYmJPSnVTMXFBWEVkb0Z3TFxuZ3A5eGlUa2lYbkVCNG5YVWVKMmhCekVGaG1KbzNnS01nckJHOFdJOTFPb2lFLzlTNHliQm96Z3dOakFNQmdOVlxuSFJNQkFmOEVBakFBTUE0R0ExVWREd0VCL3dRRUF3SUZvREFXQmdOVkhTVUJBZjhFRERBS0JnZ3JCZ0VGQlFjRFxuQVRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQW5YRnVyYTh0cnVXSURuVVNiejNna284QURLbEhkb2dCN0dkdFxuaTIzS2FLSUNJUURvT1hNN3dTWEt0TWJ3WFBUdVR0b2FDMFRaYk13V3JIS2tMTnRuVlY1TmJ3PT1cbi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0iLCJub2RlS2V5UGVtIjoiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUdIQWdFQU1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhCRzB3YXdJQkFRUWdzNzcxVzQwUFlhWmpyeko5XG5zc0g5MWJLMTdhR0V5elMrRlBoSzU3dms2aXFoUkFOQ0FBUnVaMi9UWHFVVmlRbjFiTjcwYmJPSnVTMXFBWEVkXG5vRndMZ3A5eGlUa2lYbkVCNG5YVWVKMmhCekVGaG1KbzNnS01nckJHOFdJOTFPb2lFLzlTNHliQlxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLSIsImNhQ2VydFBlbSI6Ii0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLVxuTUlJQlVEQ0IrS0FEQWdFQ0FnRUJNQW9HQ0NxR1NNNDlCQU1DTUNBeEhqQWNCZ05WQkFNTUZYUm1SbGxpYlVOMFxuTUhOclh6aEtNRVppVjJNNE56QWVGdzB5TlRFd01qY3dNVEEwTVRkYUZ3MHpOVEV3TWpjd01UQTBNVGRhTUNBeFxuSGpBY0JnTlZCQU1NRlhSbVJsbGliVU4wTUhOclh6aEtNRVppVjJNNE56QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1xuU000OUF3RUhBMElBQkFiMTVkdHA3OWVDeWcrOEVITVBIRm90cXl3aFM0V1l5aVVyTC9Pa0h1NktzQktyRXV1SVxub0tNdjAwclQxT1Budm1Xd2dFYzcyR1VBZWVobUpNZFFIZkdqSXpBaE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d1xuRGdZRFZSMFBBUUgvQkFRREFnS0VNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJSEN5eTduWnlaZ2Zjdmh3VHNqN1xubitZOWVLQ2t1YWh6ejdvem5rR21ONHNXQWlBeTIzSWVBaEVDM0k5OTJ6NUVjdFV1b1JkSm15UUVUeHRFeTdKblxubkJjUUh3PT1cbi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0iLCJqd3RQdWJsaWNLZXkiOiItLS0tLUJFR0lOIFBVQkxJQyBLRVktLS0tLVxuTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE3NjdFNzM3QThESzlQL0NQYnBMalxuY1NyLzg0TURNUUhsL2JQUVFPZkVaeFp0YzF1N1VYcWVPUG5KUVROUEZOVy9zYVhJM3NjTlZDWmw4cjc2U2pCSVxudmU0bUtvMWZVZXdGamxzaHpsZHFvU0FTS3F6b2ZyN2ZvZ1BFTWNQTmxFOTNZR3FvanV0ZTAwS2VaT3pRaWNmcFxuVmNBRHk2bkU2V2NXS2Z0M2dPeXVBYUMxcVB1S0lpTXFMcVg3MlJqUFFta1pjTFE1amhvb1NjbFIzSTZ2UU53OVxuOTFXY3RQZjZFMDNLRjdWUzlnU1A2K0V5OG12VkdleXNQTWc2b2ZvcG5Hc0thQmZnaFVDaFlyTE5ocWVoZ0o2M1xuZ0NFREoyd0xvZnJZZFhWeHFrZzZTUWltYSttcnRZMXhqcUlYOWlud2RGa2pFVUdSNUc4VSs2bnNvNlIrTFd0bFxuZHdJREFRQUJcbi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLVxuIn0=\n"
remnawave_timeout:           60
admin_email:                 "mistwork03@gmail.com"

# ============================================================
# SSH HARDENING
# ============================================================
ssh_user: "root"               # пользователь, которому кладём ключ
ssh_public_key: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXNsfxI/ETSMAh/2kBFAhJv6atFA1FWCMlHCerwjP9v mist@DESKTOP-MHS7F2K

# ============================================================
# FAIL2BAN
# ============================================================
fail2ban_bantime:  "1h"
fail2ban_findtime: "10m"
fail2ban_maxretry: 5
fail2ban_ssh_port: 22


